version: "3.0"
services:
  postgres_db:
      image: postgres:13.5
      container_name: dev-postgresql
      # build:
      #   context: ./
      #   dockerfile: Dockerfile      
      restart: always
      environment:
          - POSTGRES_USER=dev
          - POSTGRES_PASSWORD=IamDev@@246357
          - POSTGRES_DB=dev
          - POSTGRES_HOST_AUTH_METHOD=trust
      volumes:
          - ./data:/var/lib/postgresql/data
          - ./init:/docker-entrypoint-initdb.d
      ports:
          - '5432:5432'
      networks:
        - dev-network
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "dev"]
        interval: 5s
        timeout: 5s
        retries: 5
networks:
  dev-network:
    driver: bridge
volumes:
    postgres_db:
        driver: local


