<?php

namespace Dev\CodeHighlighter;

use Dev\Theme\Facades\Theme;
use Illuminate\Support\Str;

class CodeHighlighter
{
    protected static array $supportedLanguages = [
        '1c' => '1C',
        'abnf' => 'ABNF',
        'accesslog' => 'Access Log',
        'actionscript' => 'ActionScript',
        'ada' => 'Ada',
        'angelscript' => 'AngelScript',
        'apache' => 'Apache',
        'applescript' => 'AppleScript',
        'arcade' => 'Arcade',
        'arduino' => 'Arduino',
        'armasm' => 'ARM Assembly',
        'asciidoc' => 'AsciiDoc',
        'aspectj' => 'AspectJ',
        'autohotkey' => 'AutoHotkey',
        'autoit' => 'AutoIt',
        'avrasm' => 'AVR Assembly',
        'awk' => 'Awk',
        'axapta' => 'Axapta',
        'bash' => 'Bash',
        'basic' => 'Basic',
        'bnf' => 'BNF',
        'brainfuck' => 'Brainfuck',
        'c' => 'C',
        'cal' => 'Cal',
        'capnproto' => 'Cap\'n Proto',
        'ceylon' => 'Ceylon',
        'clean' => 'Clean',
        'clojure' => 'Clojure',
        'clojure-repl' => 'Clojure REPL',
        'cmake' => 'CMake',
        'coffeescript' => 'CoffeeScript',
        'coq' => 'Coq',
        'cos' => 'Cos',
        'cpp' => 'C++',
        'crmsh' => 'crmsh',
        'crystal' => 'Crystal',
        'csharp' => 'C#',
        'csp' => 'CSP',
        'css' => 'CSS',
        'd' => 'D',
        'dart' => 'Dart',
        'delphi' => 'Delphi',
        'diff' => 'Diff',
        'django' => 'Django',
        'dns' => 'DNS',
        'dockerfile' => 'Dockerfile',
        'dos' => 'DOS',
        'dsconfig' => 'dsconfig',
        'dts' => 'DTS',
        'dust' => 'Dust',
        'ebnf' => 'EBNF',
        'elixir' => 'Elixir',
        'elm' => 'Elm',
        'erb' => 'ERB',
        'erlang' => 'Erlang',
        'erlang-repl' => 'Erlang REPL',
        'excel' => 'Excel',
        'fix' => 'FIX',
        'flix' => 'Flix',
        'fortran' => 'Fortran',
        'fsharp' => 'F#',
        'gams' => 'GAMS',
        'gauss' => 'GAUSS',
        'gcode' => 'G-Code',
        'gherkin' => 'Gherkin',
        'glsl' => 'GLSL',
        'gml' => 'GML',
        'go' => 'Go',
        'golo' => 'Golo',
        'gradle' => 'Gradle',
        'graphql' => 'GraphQL',
        'groovy' => 'Groovy',
        'haml' => 'Haml',
        'handlebars' => 'Handlebars',
        'haskell' => 'Haskell',
        'haxe' => 'Haxe',
        'hsp' => 'HSP',
        'http' => 'HTTP',
        'hy' => 'Hy',
        'inform7' => 'Inform 7',
        'ini' => 'INI',
        'irpf90' => 'IRPF90',
        'isbl' => 'ISBL',
        'java' => 'Java',
        'javascript' => 'JavaScript',
        'jboss-cli' => 'JBoss CLI',
        'json' => 'JSON',
        'julia' => 'Julia',
        'julia-repl' => 'Julia REPL',
        'kotlin' => 'Kotlin',
        'lasso' => 'Lasso',
        'latex' => 'LaTeX',
        'ldif' => 'LDIF',
        'leaf' => 'Leaf',
        'less' => 'Less',
        'lisp' => 'Lisp',
        'livecodeserver' => 'LiveCode Server',
        'livescript' => 'LiveScript',
        'llvm' => 'LLVM IR',
        'lsl' => 'LSL',
        'lua' => 'Lua',
        'makefile' => 'Makefile',
        'markdown' => 'Markdown',
        'mathematica' => 'Mathematica',
        'matlab' => 'MATLAB',
        'maxima' => 'Maxima',
        'mel' => 'MEL',
        'mercury' => 'Mercury',
        'mipsasm' => 'MIPS Assembly',
        'mizar' => 'Mizar',
        'mojolicious' => 'Mojolicious',
        'monkey' => 'Monkey',
        'moonscript' => 'MoonScript',
        'n1ql' => 'N1QL',
        'nestedtext' => 'NestedText',
        'nginx' => 'Nginx',
        'nim' => 'Nim',
        'nix' => 'Nix',
        'node-repl' => 'Node REPL',
        'nsis' => 'NSIS',
        'objectivec' => 'Objective-C',
        'ocaml' => 'OCaml',
        'openscad' => 'OpenSCAD',
        'oxygene' => 'Oxygene',
        'parser3' => 'Parser3',
        'perl' => 'Perl',
        'pf' => 'PF',
        'pgsql' => 'PostgreSQL',
        'php' => 'PHP',
        'php-template' => 'PHP Template',
        'plaintext' => 'Plain Text',
        'pony' => 'Pony',
        'powershell' => 'PowerShell',
        'processing' => 'Processing',
        'profile' => 'Profile',
        'prolog' => 'Prolog',
        'properties' => 'Properties',
        'protobuf' => 'Protocol Buffers',
        'puppet' => 'Puppet',
        'purebasic' => 'PureBasic',
        'python' => 'Python',
        'python-repl' => 'Python REPL',
        'q' => 'Q',
        'qml' => 'QML',
        'r' => 'R',
        'reasonml' => 'ReasonML',
        'rib' => 'RenderMan RIB',
        'roboconf' => 'Roboconf',
        'routeros' => 'RouterOS',
        'rsl' => 'RSL',
        'ruby' => 'Ruby',
        'ruleslanguage' => 'Rules Language',
        'rust' => 'Rust',
        'sas' => 'SAS',
        'scala' => 'Scala',
        'scheme' => 'Scheme',
        'scilab' => 'Scilab',
        'scss' => 'SCSS',
        'shell' => 'Shell',
        'smali' => 'Smali',
        'smalltalk' => 'Smalltalk',
        'sml' => 'SML',
        'sqf' => 'SQF',
        'sql' => 'SQL',
        'stan' => 'Stan',
        'stata' => 'Stata',
        'step21' => 'STEP Part 21',
        'stylus' => 'Stylus',
        'subunit' => 'SubUnit',
        'swift' => 'Swift',
        'taggerscript' => 'Tagger Script',
        'tap' => 'TAP',
        'tcl' => 'Tcl',
        'thrift' => 'Thrift',
        'tp' => 'TP',
        'twig' => 'Twig',
        'typescript' => 'TypeScript',
        'vala' => 'Vala',
        'vbnet' => 'VB.Net',
        'vbscript' => 'VBScript',
        'vbscript-html' => 'VBScript HTML',
        'verilog' => 'Verilog',
        'vhdl' => 'VHDL',
        'vim' => 'Vim',
        'wasm' => 'WebAssembly',
        'wren' => 'Wren',
        'x86asm' => 'x86 Assembly',
        'xl' => 'XL',
        'xml' => 'XML',
        'xquery' => 'XQuery',
        'yaml' => 'YAML',
        'zephir' => 'Zephir',
    ];

    protected static array $defaultLanguages = [];

    protected static array $supportedThemes = [
        'base16-3024' => 'Base16 3024',
        'base16-apathy' => 'Base16 Apathy',
        'base16-apprentice' => 'Base16 Apprentice',
        'base16-ashes' => 'Base16 Ashes',
        'base16-atelier-cave' => 'Base16 Atelier Cave',
        'base16-atelier-cave-light' => 'Base16 Atelier Cave Light',
        'base16-atelier-dune' => 'Base16 Atelier Dune',
        'base16-atelier-dune-light' => 'Base16 Atelier Dune Light',
        'base16-atelier-estuary' => 'Base16 Atelier Estuary',
        'base16-atelier-estuary-light' => 'Base16 Atelier Estuary Light',
        'base16-atelier-forest' => 'Base16 Atelier Forest',
        'base16-atelier-forest-light' => 'Base16 Atelier Forest Light',
        'base16-atelier-heath' => 'Base16 Atelier Heath',
        'base16-atelier-heath-light' => 'Base16 Atelier Heath Light',
        'base16-atelier-lakeside' => 'Base16 Atelier Lakeside',
        'base16-atelier-lakeside-light' => 'Base16 Atelier Lakeside Light',
        'base16-atelier-plateau' => 'Base16 Atelier Plateau',
        'base16-atelier-plateau-light' => 'Base16 Atelier Plateau Light',
        'base16-atelier-savanna' => 'Base16 Atelier Savanna',
        'base16-atelier-savanna-light' => 'Base16 Atelier Savanna Light',
        'base16-atelier-seaside' => 'Base16 Atelier Seaside',
        'base16-atelier-seaside-light' => 'Base16 Atelier Seaside Light',
        'base16-atelier-sulphurpool' => 'Base16 Atelier Sulphurpool',
        'base16-atelier-sulphurpool-light' => 'Base16 Atelier Sulphurpool Light',
        'base16-atlas' => 'Base16 Atlas',
        'base16-bespin' => 'Base16 Bespin',
        'base16-black-metal' => 'Base16 Black Metal',
        'base16-black-metal-bathory' => 'Base16 Black Metal Bathory',
        'base16-black-metal-burzum' => 'Base16 Black Metal Burzum',
        'base16-black-metal-dark-funeral' => 'Base16 Black Metal Dark Funeral',
        'base16-black-metal-gorgoroth' => 'Base16 Black Metal Gorgoroth',
        'base16-black-metal-immortal' => 'Base16 Black Metal Immortal',
        'base16-black-metal-khold' => 'Base16 Black Metal Khold',
        'base16-black-metal-marduk' => 'Base16 Black Metal Marduk',
        'base16-black-metal-mayhem' => 'Base16 Black Metal Mayhem',
        'base16-black-metal-nile' => 'Base16 Black Metal Nile',
        'base16-black-metal-venom' => 'Base16 Black Metal Venom',
        'base16-brewer' => 'Base16 Brewer',
        'base16-bright' => 'Base16 Bright',
        'base16-brogrammer' => 'Base16 Brogrammer',
        'base16-brush-trees' => 'Base16 Brush Trees',
        'base16-brush-trees-dark' => 'Base16 Brush Trees Dark',
        'base16-chalk' => 'Base16 Chalk',
        'base16-circus' => 'Base16 Circus',
        'base16-classic-dark' => 'Base16 Classic Dark',
        'base16-classic-light' => 'Base16 Classic Light',
        'base16-codeschool' => 'Base16 Codeschool',
        'base16-colors' => 'Base16 Colors',
        'base16-cupcake' => 'Base16 Cupcake',
        'base16-cupertino' => 'Base16 Cupertino',
        'base16-danqing' => 'Base16 Danqing',
        'base16-darcula' => 'Base16 Darcula',
        'base16-dark-violet' => 'Base16 Dark Violet',
        'base16-darkmoss' => 'Base16 Darkmoss',
        'base16-darktooth' => 'Base16 Darktooth',
        'base16-decaf' => 'Base16 Decaf',
        'base16-default-dark' => 'Base16 Default Dark',
        'base16-default-light' => 'Base16 Default Light',
        'base16-dirtysea' => 'Base16 Dirtysea',
        'base16-dracula' => 'Base16 Dracula',
        'base16-edge-dark' => 'Base16 Edge Dark',
        'base16-edge-light' => 'Base16 Edge Light',
        'base16-eighties' => 'Base16 Eighties',
        'base16-embers' => 'Base16 Embers',
        'base16-equilibrium-dark' => 'Base16 Equilibrium Dark',
        'base16-equilibrium-gray-dark' => 'Base16 Equilibrium Gray Dark',
        'base16-equilibrium-gray-light' => 'Base16 Equilibrium Gray Light',
        'base16-equilibrium-light' => 'Base16 Equilibrium Light',
        'base16-espresso' => 'Base16 Espresso',
        'base16-eva' => 'Base16 Eva',
        'base16-eva-dim' => 'Base16 Eva Dim',
        'base16-flat' => 'Base16 Flat',
        'base16-framer' => 'Base16 Framer',
        'base16-fruit-soda' => 'Base16 Fruit Soda',
        'base16-gigavolt' => 'Base16 Gigavolt',
        'base16-github' => 'Base16 GitHub',
        'base16-google-dark' => 'Base16 Google Dark',
        'base16-google-light' => 'Base16 Google Light',
        'base16-grayscale-dark' => 'Base16 Grayscale Dark',
        'base16-grayscale-light' => 'Base16 Grayscale Light',
        'base16-green-screen' => 'Base16 Green Screen',
        'base16-gruvbox-dark-hard' => 'Base16 Gruvbox Dark Hard',
        'base16-gruvbox-dark-medium' => 'Base16 Gruvbox Dark Medium',
        'base16-gruvbox-dark-pale' => 'Base16 Gruvbox Dark Pale',
        'base16-gruvbox-dark-soft' => 'Base16 Gruvbox Dark Soft',
        'base16-gruvbox-light-hard' => 'Base16 Gruvbox Light Hard',
        'base16-gruvbox-light-medium' => 'Base16 Gruvbox Light Medium',
        'base16-gruvbox-light-soft' => 'Base16 Gruvbox Light Soft',
        'base16-hardcore' => 'Base16 Hardcore',
        'base16-harmonic16-dark' => 'Base16 Harmonic16 Dark',
        'base16-harmonic16-light' => 'Base16 Harmonic16 Light',
        'base16-heetch-dark' => 'Base16 Heetch Dark',
        'base16-heetch-light' => 'Base16 Heetch Light',
        'base16-helios' => 'Base16 Helios',
        'base16-hopscotch' => 'Base16 Hopscotch',
        'base16-horizon-dark' => 'Base16 Horizon Dark',
        'base16-horizon-light' => 'Base16 Horizon Light',
        'base16-humanoid-dark' => 'Base16 Humanoid Dark',
        'base16-humanoid-light' => 'Base16 Humanoid Light',
        'base16-ia-dark' => 'Base16 IA Dark',
        'base16-ia-light' => 'Base16 IA Light',
        'base16-icy-dark' => 'Base16 Icy Dark',
        'base16-ir-black' => 'Base16 IR Black',
        'base16-isotope' => 'Base16 Isotope',
        'base16-kimber' => 'Base16 Kimber',
        'base16-london-tube' => 'Base16 London Tube',
        'base16-macintosh' => 'Base16 Macintosh',
        'base16-marrakesh' => 'Base16 Marrakesh',
        'base16-materia' => 'Base16 Materia',
        'base16-material' => 'Base16 Material',
        'base16-material-darker' => 'Base16 Material Darker',
        'base16-material-lighter' => 'Base16 Material Lighter',
        'base16-material-palenight' => 'Base16 Material Palenight',
        'base16-material-vivid' => 'Base16 Material Vivid',
        'base16-mellow-purple' => 'Base16 Mellow Purple',
        'base16-mexico-light' => 'Base16 Mexico Light',
        'base16-mocha' => 'Base16 Mocha',
        'base16-monokai' => 'Base16 Monokai',
        'base16-nebula' => 'Base16 Nebula',
        'base16-nord' => 'Base16 Nord',
        'base16-nova' => 'Base16 Nova',
        'base16-ocean' => 'Base16 Ocean',
        'base16-oceanicnext' => 'Base16 OceanicNext',
        'base16-one-light' => 'Base16 One Light',
        'base16-onedark' => 'Base16 OneDark',
        'base16-outrun-dark' => 'Base16 Outrun Dark',
        'base16-papercolor-dark' => 'Base16 PaperColor Dark',
        'base16-papercolor-light' => 'Base16 PaperColor Light',
        'base16-paraiso' => 'Base16 Paraiso',
        'base16-pasque' => 'Base16 Pasque',
        'base16-phd' => 'Base16 PhD',
        'base16-pico' => 'Base16 Pico',
        'base16-pop' => 'Base16 Pop',
        'base16-porple' => 'Base16 Porple',
        'base16-qualia' => 'Base16 Qualia',
        'base16-railscasts' => 'Base16 Railscasts',
        'base16-rebecca' => 'Base16 Rebecca',
        'base16-ros-pine' => 'Base16 Rosé Pine',
        'base16-ros-pine-dawn' => 'Base16 Rosé Pine Dawn',
        'base16-ros-pine-moon' => 'Base16 Rosé Pine Moon',
        'base16-sagelight' => 'Base16 Sagelight',
        'base16-sandcastle' => 'Base16 Sandcastle',
        'base16-seti-ui' => 'Base16 Seti UI',
        'base16-shapeshifter' => 'Base16 Shapeshifter',
        'base16-silk-dark' => 'Base16 Silk Dark',
        'base16-silk-light' => 'Base16 Silk Light',
        'base16-snazzy' => 'Base16 Snazzy',
        'base16-solar-flare' => 'Base16 Solar Flare',
        'base16-solar-flare-light' => 'Base16 Solar Flare Light',
        'base16-solarized-dark' => 'Base16 Solarized Dark',
        'base16-solarized-light' => 'Base16 Solarized Light',
        'base16-spacemacs' => 'Base16 Spacemacs',
        'base16-summercamp' => 'Base16 Summer Camp',
        'base16-summerfruit-dark' => 'Base16 Summerfruit Dark',
        'base16-summerfruit-light' => 'Base16 Summerfruit Light',
        'base16-synth-midnight-terminal-dark' => 'Base16 Synth Midnight Terminal Dark',
        'base16-synth-midnight-terminal-light' => 'Base16 Synth Midnight Terminal Light',
        'base16-tango' => 'Base16 Tango',
        'base16-tender' => 'Base16 Tender',
        'base16-tomorrow' => 'Base16 Tomorrow',
        'base16-tomorrow-night' => 'Base16 Tomorrow Night',
        'base16-twilight' => 'Base16 Twilight',
        'base16-unikitty-dark' => 'Base16 Unikitty Dark',
        'base16-unikitty-light' => 'Base16 Unikitty Light',
        'base16-vulcan' => 'Base16 Vulcan',
        'base16-windows-10' => 'Base16 Windows 10',
        'base16-windows-10-light' => 'Base16 Windows 10 Light',
        'base16-windows-95' => 'Base16 Windows 95',
        'base16-windows-95-light' => 'Base16 Windows 95 Light',
        'base16-windows-high-contrast' => 'Base16 Windows High Contrast',
        'base16-windows-high-contrast-light' => 'Base16 Windows High Contrast Light',
        'base16-windows-nt' => 'Base16 Windows NT',
        'base16-windows-nt-light' => 'Base16 Windows NT Light',
        'base16-woodland' => 'Base16 Woodland',
        'base16-xcode-dusk' => 'Base16 Xcode Dusk',
        'base16-zenburn' => 'Base16 Zenburn',
        '1c-light' => '1C Light',
        'a11y-dark' => 'A11y Dark',
        'a11y-light' => 'A11y Light',
        'agate' => 'Agate',
        'an-old-hope' => 'An Old Hope',
        'androidstudio' => 'Android Studio',
        'arduino-light' => 'Arduino Light',
        'arta' => 'Arta',
        'ascetic' => 'Ascetic',
        'atom-one-dark' => 'Atom One Dark',
        'atom-one-dark-reasonable' => 'Atom One Dark Reasonable',
        'atom-one-light' => 'Atom One Light',
        'brown-paper' => 'Brown Paper',
        'codepen-embed' => 'CodePen Embed',
        'color-brewer' => 'Color Brewer',
        'dark' => 'Dark',
        'default' => 'Default',
        'devibeans' => 'Devibeans',
        'docco' => 'Docco',
        'far' => 'Far',
        'felipec' => 'Felipec',
        'foundation' => 'Foundation',
        'github' => 'GitHub',
        'github-dark' => 'GitHub Dark',
        'github-dark-dimmed' => 'GitHub Dark Dimmed',
        'gml' => 'GML',
        'googlecode' => 'Google Code',
        'gradient-dark' => 'Gradient Dark',
        'gradient-light' => 'Gradient Light',
        'grayscale' => 'Grayscale',
        'hybrid' => 'Hybrid',
        'idea' => 'IDEA',
        'intellij-light' => 'IntelliJ Light',
        'ir-black' => 'IR Black',
        'isbl-editor-dark' => 'ISBL Editor Dark',
        'isbl-editor-light' => 'ISBL Editor Light',
        'kimbie-dark' => 'Kimbie Dark',
        'kimbie-light' => 'Kimbie Light',
        'lightfair' => 'Lightfair',
        'lioshi' => 'Lioshi',
        'magula' => 'Magula',
        'mono-blue' => 'Mono Blue',
        'monokai' => 'Monokai',
        'monokai-sublime' => 'Monokai Sublime',
        'night-owl' => 'Night Owl',
        'nnfx-dark' => 'NNFX Dark',
        'nnfx-light' => 'NNFX Light',
        'nord' => 'Nord',
        'obsidian' => 'Obsidian',
        'panda-syntax-dark' => 'Panda Syntax Dark',
        'panda-syntax-light' => 'Panda Syntax Light',
        'paraiso-dark' => 'Paraiso Dark',
        'paraiso-light' => 'Paraiso Light',
        'pojoaque' => 'Pojoaque',
        'purebasic' => 'PureBasic',
        'qtcreator-dark' => 'Qt Creator Dark',
        'qtcreator-light' => 'Qt Creator Light',
        'rainbow' => 'Rainbow',
        'routeros' => 'RouterOS',
        'school-book' => 'School Book',
        'shades-of-purple' => 'Shades of Purple',
        'srcery' => 'Srcery',
        'stackoverflow-dark' => 'Stack Overflow Dark',
        'stackoverflow-light' => 'Stack Overflow Light',
        'sunburst' => 'Sunburst',
        'tokyo-night-dark' => 'Tokyo Night Dark',
        'tokyo-night-light' => 'Tokyo Night Light',
        'tomorrow-night-blue' => 'Tomorrow Night Blue',
        'tomorrow-night-bright' => 'Tomorrow Night Bright',
        'vs' => 'Visual Studio',
        'vs2015' => 'Visual Studio 2015',
        'xcode' => 'Xcode',
        'xt256' => 'XT256',
    ];

    protected static string $defaultTheme = 'github-dark';

    protected static string $defaultSettingPrefix = 'code_highlighter';

    public static function getSettingKey(string $key): string
    {
        return static::$defaultSettingPrefix . '_' . $key;
    }

    public static function getSetting(string $key, mixed $default): mixed
    {
        return setting(self::getSettingKey($key), $default);
    }

    public static function getSupportedLanguages(): array
    {
        return static::$supportedLanguages;
    }

    public static function getSupportedThemes(): array
    {
        return static::$supportedThemes;
    }

    public static function getDefaultTheme(): string
    {
        return static::$defaultTheme;
    }

    public static function getCurrentTheme(): string
    {
        return self::getSetting('theme', self::getDefaultTheme());
    }

    public static function getCurrentSupportedLanguages(): array
    {
        return json_decode(self::getSetting('languages', '[]'), true) ?: self::$defaultLanguages;
    }

    public static function registerAssets(): void
    {
        $prefix = 'vendor/core/plugins/code-highlighter/libraries/hljs/';

        $currentTheme = self::getCurrentTheme();
        $stylesheets = [
            $prefix . 'code-highlighter.min.css',
        ];

        if (Str::startsWith($currentTheme, 'base16-')) {
            $stylesheets[] = $prefix . 'styles/base16/' . Str::after($currentTheme, 'base16-') . '.min.css';
        } else {
            $stylesheets[] = $prefix . 'styles/' . $currentTheme . '.min.css';
        }

        foreach ($stylesheets as $key => $stylesheet) {
            Theme::asset()->add('highlight-stylesheet-' . $key, $stylesheet);
        }

        Theme::asset()->container('footer')->add('highlight-js', $prefix . 'highlight.min.js');

        $scripts = array_map(function ($script) use ($prefix) {
            return $prefix . 'languages/' . $script . '.min.js';
        }, self::getCurrentSupportedLanguages());

        foreach ($scripts as $key => $script) {
            Theme::asset()->container('footer')->add('highlight-js-' . $key, $script);
        }

        app()->instance('registered.plugins.code-highlighter', true);
    }

    public static function renderInitialScript(): string
    {
        if (! self::isRegistered()) {
            return '';
        }

        return trim(<<<'HTML'
            <script>document.addEventListener('DOMContentLoaded', function () { hljs.highlightAll(); });</script>
        HTML);
    }

    public static function isRegistered(): bool
    {
        return (bool) app('registered.plugins.code-highlighter');
    }
}
